name: condaenv
channels:
 - nvidia
 - conda-forge
 - fastai
dependencies:
###############################
# planetary computer packages #
###############################
 - python=3.9*
 - pip=20
 - bottleneck
 - eofs
 - esmpy
 - fsspec
 - geocube
 - gsw
 - lz4
 - metpy
 - numcodecs
 - numpy
 - pandas
 - pydap
 - pyepsg
 - pygeos
 - rasterio
 - rechunker
 - scikit-image
 - scikit-learn
 - scipy
 - shapely
 - xarray-spatial>=0.2.4
 - xarray>=0.18.0
 - xarrayutils
 - zarr
#########################
# deep learning         #
#########################
 - fastai
 - pytorch=1.9.0
 - torchvision=0.9.1
 - pytorch-lightning
 - segmentation-models-pytorch
 - timm
 - albumentations
#########################
# competition specific  #
#########################
 - loguru
 - pillow
 - pytest
 - tqdm
 - typer
#########################
# install with pip      #
#########################
 - pip:
   - tifffile
